library(conflicted)
library(dotenv)
library(drake)

library(anytime)
library(coda)
library(dgof)
library(dplyr)
library(forcats)
library(ggplot2)
library(ggpubr)
library(ggthemes)
library(kableExtra)
library(KSgeneral)
library(lubridate)
library(MASS)
library(mvtnorm)
library(nimble)
library(parallel)
library(R.matlab)
library(stringr)
library(tidyr)
library(XML)

conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("setdiff", "base")
conflict_prefer("intersect", "base")