#!/bin/sh

#SBATCH --job-name fulltag_fit
#SBATCH --partition common
#SBATCH --account gelfandlab
#SBATCH --mail-type ALL
#SBATCH --mail-user joshua.hewitt@duke.edu
#SBATCH --ntasks 1
#SBATCH --time 96:00:00

echo "Nodes used: $SLURM_JOB_NODELIST"

date
START=`date +%s`

R CMD BATCH --no-save --no-restore make.R ${SLURM_JOB_NAME}.Rout

END=`date +%s`
date

ELAPSED=$(( $END - $START ))
echo "Elapsed time (hrs): $(echo "scale=10; $ELAPSED/3600" | bc)"
